### PR TITLE
Fix link to Mjolnir

### PR DESCRIPTION
**Pull request by progval**

### CODE REVIEW

**Comment by Gnuxie** [comment]
@progval can you add a sign off line to confirm that you have [read](https://github.com/Gnuxie/Draupnir/blob/main/CONTRIBUTING.md#sign-off) and that you are happy with submitting your contribution under the Apache-2.0 License found in [NOTICE](https://github.com/Gnuxie/Draupnir/blob/main/NOTICE#L30) ?

I know it is only readme change but have to be diligent

**Comment by progval** [comment]
It's implied by Github's ToS... https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license but yes sure.

Do you have a "real name" policy like m.o?

**Comment by Gnuxie** [comment]
Naa don't care about real names

**Comment by Gnuxie** [comment]
Thanks <3

**Pull request merged**
