### PR TITLE
.editorconfig: fix invalid value s/off/unset/g

### PR DESCRIPTION
**Pull request by Mikaela**
This was breaking prettier and neovim as apparently off was invalid value

### CODE REVIEW

**Comment by Gnuxie** [comment]
Do they have a spec anywhere. Their wiki suggests that `unset` is also invalid. https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_size

**Comment by Gnuxie** [comment]
Ok actually i cant' read https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#current-universal-properties

**Review by Gnuxie — APPROVED** [review]

**Comment by Mikaela** [comment]
Also from your link: https://spec.editorconfig.org/

**Comment by Gnuxie** [comment]
Thanks

**Pull request merged**
